# Use root/example as user/password credentials
version: "3.1"
services:
  client:
    container_name: client
    env_file:
      - ./.env
    build:
      context: ./whipple/client
    ports:
      - 3000:3000
    depends_on:
      - server
  db:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    container_name: server
    env_file:
      - ./.env
    volumes:
      - ./whipple/server/src/alembic:/src/alembic
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./whipple/server
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
volumes:
    postgres:
